"""AddressTypeInSnaphosts

Revision ID: 4a3940c13997
Revises: f9716b9414d3
Create Date: 2021-04-20 10:10:31.247842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3940c13997'
down_revision = 'f9716b9414d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_snapshots', sa.Column('address_type', sa.INTEGER(), nullable=True))
    op.add_column('token_snapshots', sa.Column('wallet_address', sa.VARCHAR(length=50), nullable=False))
    op.drop_index('ix_token_snapshots_address', table_name='token_snapshots')
    op.drop_constraint('uq_sn', 'token_snapshots', type_='unique')
    op.create_unique_constraint('uq_sn', 'token_snapshots', ['wallet_address'])
    op.create_index(op.f('ix_token_snapshots_wallet_address'), 'token_snapshots', ['wallet_address'], unique=False)
    op.drop_column('token_snapshots', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_snapshots', sa.Column('address', mysql.VARCHAR(length=50), nullable=False))
    op.drop_index(op.f('ix_token_snapshots_wallet_address'), table_name='token_snapshots')
    op.drop_constraint('uq_sn', 'token_snapshots', type_='unique')
    op.create_unique_constraint('uq_sn', 'token_snapshots', ['address'])
    op.create_index('ix_token_snapshots_address', 'token_snapshots', ['address'], unique=False)
    op.drop_column('token_snapshots', 'wallet_address')
    op.drop_column('token_snapshots', 'address_type')
    # ### end Alembic commands ###
