"""UserComments

Revision ID: 50417ee80aa2
Revises: 7faa48f4bb16
Create Date: 2021-04-06 10:12:31.585813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50417ee80aa2'
down_revision = '7faa48f4bb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comments',
    sa.Column('row_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('row_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('row_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index(op.f('ix_user_comments_wallet_address'), 'user_comments', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_comments_wallet_address'), table_name='user_comments')
    op.drop_table('user_comments')
    # ### end Alembic commands ###
