"""Schema

Revision ID: d0147e793f11
Revises: 
Create Date: 2021-04-05 14:40:32.525284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0147e793f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('block_number', sa.BIGINT(), nullable=False),
    sa.Column('amount_held_in_cogs', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('snap_shot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_wallet_address'), 'snapshots', ['wallet_address'], unique=False)
    op.create_table('transfer_info',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transfer_time', sa.DateTime(), nullable=False),
    sa.Column('transfer_fees', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('transfer_transaction', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transfer_amount_in_cogs', sa.DECIMAL(precision=19, scale=8), nullable=False),
    sa.Column('transfer_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_info_wallet_address'), 'transfer_info', ['wallet_address'], unique=False)
    op.create_table('user_access_details',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_access_details_wallet_address'), 'user_access_details', ['wallet_address'], unique=False)
    op.create_table('user_comments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_comments_wallet_address'), 'user_comments', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_comments_wallet_address'), table_name='user_comments')
    op.drop_table('user_comments')
    op.drop_index(op.f('ix_user_access_details_wallet_address'), table_name='user_access_details')
    op.drop_table('user_access_details')
    op.drop_index(op.f('ix_transfer_info_wallet_address'), table_name='transfer_info')
    op.drop_table('transfer_info')
    op.drop_index(op.f('ix_snapshots_wallet_address'), table_name='snapshots')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
