"""UniqueAddressOnly

Revision ID: f9716b9414d3
Revises: b57d43425d56
Create Date: 2021-04-19 13:40:29.746146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9716b9414d3'
down_revision = 'b57d43425d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sn', 'token_snapshots', type_='unique')
    op.create_unique_constraint('uq_sn', 'token_snapshots', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sn', 'token_snapshots', type_='unique')
    op.create_unique_constraint('uq_sn', 'token_snapshots', ['address', 'block_number'])
    # ### end Alembic commands ###
